### ISSUE TITLE
TQDM flashing behavior for small parts 

### ISSUE THREAD

**Issue by lbeckman314** [anvilproject/drs_downloader#21]
Add option to hide TQDM download progress for small parts to avoid flashing display.

https://github.com/anvilproject/drs_downloader/pull/15#discussion_r1053723547

**Comment by matthewpeterkort** [comment]
[fixed here](https://github.com/anvilproject/drs_downloader/blob/feature/testing-dev/drs_downloader/manager.py#L169-L172) and [here](https://github.com/anvilproject/drs_downloader/blob/feature/testing-dev/drs_downloader/manager.py#L217-L218) demo with ```drs_download terra --manifest-path tests/fixtures/terra-data.tsv```from feature/test-dev branch

**Comment by matthewpeterkort** [comment]
Revisited this fix and fixed a small issue with mixed file size downloads not showing progress of large file downloads addressed [here.](https://github.com/anvilproject/drs_downloader/commit/3281363579e3c20a646633fe9e877843c756a221)
