### ISSUE TITLE
Inadequate identification of DRS URIs that cannot be resolved or downloaded and why

### ISSUE THREAD

**Issue by mbaumann-broad** [anvilproject/drs_downloader#47]
# Current Behavior
If/when the input includes DRS URIs that cannot be successfully resolved to metadata or downloaded, no information is provided about these in the console output or the drs_downloader.log file

# Desired Behavior
If/when the input includes DRS URIs that cannot be successfully resolved to metadata or downloaded:
* The problematic DRS URI and corresponding error message should be output to the user/console
* The problematic DRS URI and corresponding error message and stack trace should be output to the drs_downloader.log file

# Found In
drs_downloader v0.1.5-rc.11 running on macOS

**Comment by matthewpeterkort** [comment]
Addressed and tested in https://github.com/anvilproject/drs_downloader/commit/a39534a6a26a1adb1302f08031fd488fd98f9847.

Will make a new tagged commit after finishing up the high priority issues
