### ISSUE TITLE
Logging is inadequate to enable successful diagnostic/troubleshooting

### ISSUE THREAD

**Issue by mbaumann-broad** [anvilproject/drs_downloader#48]
# Current Behavior
Nothing is being written to the drs_downloader.log, even when there are errors in the download (such as unresolvable DRS URIs)

# Desired Behavior
To enable effective support, including diagnosing /troubleshooting problems, the drs_downloader.log file must contain:

- All the information output to the user/console
- Date/timestamps for all log entries
- Stack traces for all errors that occur

# Found In
drs_downloader v0.1.5-rc.11 on running on macOS

**Comment by matthewpeterkort** [comment]
Looking over this again one of the the main issues is that the drs_downloader.log file should log everything and currently it just mirrors the normal logging options. So if the user doesn't specify the -v flag there aren't many logs to begin with. 

Will try to get a fix for this
