### ISSUE TITLE
Incorrect identification of AnVIL DRS URIs

### ISSUE THREAD

**Issue by mbaumann-broad** [anvilproject/drs_downloader#49]
# Current Behavior
Currently, the drs_downloader tries to identify AnVIL DRS URIs as follows:
https://github.com/anvilproject/drs_downloader/blob/ebd2117bee6314f9cc548a2f72e8aebe67560b56/drs_downloader/clients/terra.py#L138C1-L139C65
```
        if drs_object.self_uri.startswith("drs://dg.ANV0:dg.ANV0") or \
           drs_object.self_uri.startswith("drs://drs.anv0:v2_"):
```
The above is overly restrictive. 

# Desired Behavior
As documented [here](https://docs.google.com/document/d/1nqS_QVdot3qsSIoGz_IAO62zYsZNlznqzy7ZEudZZNc/edit#heading=h.scywklsox3rl), AnVIL DRS URIs are to be identified by:

1. Case-shifting the DRS URI to lowercase
2. Checking that the DRS URI starts with either: “drs://drs.anv0:”  “drs://dg.anv0:” No portion of the DRS identifier (after the colon) should be included in the check.

# Implementation Note
A function should be created for checking if a given DRS URI is an AnVIL DRS URI, as this test will need to be used in multiple places in the drs_downloader code.

**Comment by matthewpeterkort** [comment]
Resolved in https://github.com/anvilproject/drs_downloader/commit/a39534a6a26a1adb1302f08031fd488fd98f9847.
